import { nodeModuleNameResolver } from 'typescript'

export const dataNavbar = [
  {
    title: 'Trang chủ',
    path: '/',
    id: 1,
    subMenu: null,
  },
  // {
  //   title: 'Pages',
  //   path: '/pages',
  //   id: 2,
  //   subMenu: null,
  // },
  {
    title: 'Sản phẩm',
    path: '/product',
    id: 3,
    subMenu: null,
  },
  // {
  //   title: 'Blog',
  //   path: '/blog',
  //   id: 4,
  //   subMenu: null,
  // // },
  // {
  //   title: 'Shop',
  //   path: '/shop',
  //   id: 5,
  //   subMenu: null,
  // },
  {
    title: 'Liên hệ',
    path: '/contact',
    id: 6,
    subMenu: null,
  },
]

export const DataCarousel = [
  {
    text: 'Best Furniture For Your Castle',
    title: 'New Furniture Collection Trends in 2023',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae eos molestias ullam repudiandae corrupti explicabo laudantiumdelectus reiciendis ipsum aliquam mollitia vero aut odit sequi exercitationem, tempora, sapiente, sit quis?',
    saleOf: '50%',
    image: 'http://localhost:8080/image/Red-Motorcycle-Transparent-PNG.png',
    href: '#',
  },
  {
    text: 'Best Furniture For Your Castle',
    title: 'New Furniture Collection Trends in 2023',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae eos molestias ullam repudiandae corrupti explicabo laudantiumdelectus reiciendis ipsum aliquam mollitia vero aut odit sequi exercitationem, tempora, sapiente, sit quis?',
    saleOf: null,
    image: 'images/image-3.png',
    href: '#',
  },
  {
    text: 'Best Furniture For Your Castle',
    title: 'New Furniture Collection Trends in 2023',
    description:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Quae eos molestias ullam repudiandae corrupti explicabo laudantiumdelectus reiciendis ipsum aliquam mollitia vero aut odit sequi exercitationem, tempora, sapiente, sit quis?',
    saleOf: '50%',
    image: 'images/image-25.png',
    href: '#',
  },
]
export const DataFeaturedProducts = [
  {
    id: 1,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    image: 'images/featuredProducts-1.png',
  },
  {
    id: 2,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    image: 'images/featuredProducts-2.png',
  },
  {
    id: 3,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    image: 'images/featuredProducts-3.png',
  },
  {
    id: 4,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    image: 'images/featuredProducts-4.png',
  },
  {
    id: 5,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    image: 'images/featuredProducts-1.png',
  },
  {
    id: 6,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    image: 'images/featuredProducts-2.png',
  },
  {
    id: 7,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    image: 'images/featuredProducts-3.png',
  },
  {
    id: 8,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    image: 'images/featuredProducts-4.png',
  },
]
export const DataTabsLeatestProduct = [
  {
    title: 'XE CỘ',
    id: 1,
    key: 'XE-CO',
  },
  {
    title: 'THIẾT BỊ DIỆN TỬ',
    id: 2,
    key: 'THIET-BI-DIEN-TU',
  },
  {
    title: 'ĐỒ GIA DỤNG',
    id: 3,
    key: 'DO-GIA-DUNG',
  },
  {
    title: 'ĐỒ DÙNG VĂN PHÒNG',
    id: 4,
    key: 'DO-DUNG-VAN-PHONG',
  },
]
export const DataLeatestProducts = [
  {
    title: 'Comfort Handy Craft',
    price: 42,
    old_price: 65,
    sale: false,
    id: 1,
    image: 'images/leatest-1.png',
  },
  {
    title: 'Comfort Handy Craft',
    price: 42,
    old_price: 65,
    sale: true,
    id: 2,
    image: 'images/leatest-4.png',
  },
  {
    title: 'Comfort Handy Craft',
    price: 42,
    old_price: 65,
    sale: false,
    id: 3,
    image: 'images/leatest-3.png',
  },
  {
    title: 'Comfort Handy Craft',
    price: 42,
    old_price: 65,
    sale: true,
    id: 4,
    image: 'images/leatest-4.png',
  },
  {
    title: 'Comfort Handy Craft',
    price: 42,
    old_price: 65,
    sale: false,
    id: 5,
    image: 'images/leatest-5.png',
  },
  {
    title: 'Comfort Handy Craft',
    price: 42,
    old_price: 65,
    sale: true,
    id: 6,
    image: 'images/leatest-6.png',
  },
]
export const DataOffer = [
  {
    id: 1,
    image: 'images/free-delivery-1.png',
    title: '24/7 Support',
    description: 'Sint reprehenderit minim tempor excepteur. Irure consequat magna enim excepteur.',
  },
  {
    id: 2,
    image: 'images/cashback-1.png',
    title: '24/7 Support',
    description: 'Sint reprehenderit minim tempor excepteur. Irure consequat magna enim excepteur.',
  },
  {
    id: 3,
    image: 'images/Group.png',
    title: '24/7 Support',
    description: 'Sint reprehenderit minim tempor excepteur. Irure consequat magna enim excepteur.',
  },
  {
    id: 4,
    image: 'images/24-hours-support-1.png',
    title: '24/7 Support',
    description: 'Sint reprehenderit minim tempor excepteur. Irure consequat magna enim excepteur.',
  },
]
export const DataBanner = [
  {
    id: 1,
    image: 'images/banner-1.png',
    title: 'Unique Feature Of leatest & Trending Products',
    description: [
      {
        content: 'All frames constructed with hardwood solids and laminates',
        color: '#F52B70',
      },
      {
        content: 'Reinforced with double wood dowels, glue, screw - nails corner blocks and machine nails',
        color: '#2B2BF5',
      },
      {
        content: 'Arms, backs and seats are structurally reinforced',
        color: '#2BF5CC',
      },
    ],
    name: 'B&B Italian Sofa',
    price: 32,
  },
]
export const DataTrending = [
  {
    id: 1,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    price: 32,
    old_price: 42,
    image: 'images/trending-1.png',
  },
  {
    id: 2,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    price: 32,
    old_price: 42,
    image: 'images/trending-2.png',
  },
  {
    id: 3,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    price: 32,
    old_price: 42,
    image: 'images/trending-3.png',
  },
  {
    id: 4,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    price: 32,
    old_price: 42,
    image: 'images/trending-4.png',
  },
]
export const DataTabDiscountItem = ['Wood Chair', 'Plastic Chair', 'Sofa Collection']
export const DataDiscountItem = [
  {
    id: 1,
    image: 'images/discount.png',
    title: '20% Discount Of All Product',
    text: 'Eams Sofa Compact',
    description: 'Irure non voluptate sit commodo adipisicing in consequat dolor cillum deserunt fugiat officia. ',
    detail: ['Material expose like metals', 'Clear lines and geomatric figures', 'Simple neutral colours.', 'Material expose like metals'],
  },
  {
    id: 2,
    image: 'images/discount.png',
    title: '20% Discount Of All Product',
    text: 'Eams Sofa Compact',
    description: 'Irure non voluptate sit commodo adipisicing in consequat dolor cillum deserunt fugiat officia. ',
    detail: ['Material expose like metals', 'Clear lines and geomatric figures', 'Simple neutral colours.', 'Material expose like metals'],
  },
  {
    id: 3,
    image: 'images/discount.png',
    title: '20% Discount Of All Product',
    text: 'Eams Sofa Compact',
    description: 'Irure non voluptate sit commodo adipisicing in consequat dolor cillum deserunt fugiat officia. ',
    detail: ['Material expose like metals', 'Clear lines and geomatric figures', 'Simple neutral colours.', 'Material expose like metals'],
  },
]
export const DataTopCategories = [
  {
    id: 1,
    title: 'Mini LCW Chair',
    price: 56,
    old_price: null,
    image: 'images/categories-1.png',
  },
  {
    id: 2,
    title: 'Mini LCW Chair',
    price: 56,
    old_price: null,
    image: 'images/categories-1.png',
  },
  {
    id: 3,
    title: 'Mini LCW Chair',
    price: 56,
    old_price: null,
    image: 'images/categories-1.png',
  },
  {
    id: 4,
    title: 'Mini LCW Chair',
    price: 56,
    old_price: null,
    image: 'images/categories-1.png',
  },
]
export const DataAdvertisement = [
  {
    title: 'Get Leatest Update By subcribe Our Newsletter',
    backgroundImage: 'images/Rectangle-102.png',
    href: '#',
  },
]
export const DataBlog = [
  {
    id: 1,
    date: '21 August, 2020',
    name: 'SaberAli',
    title: 'Top esssential Trends in 2021',
    description: 'More off this less hello samlande lied much over tightly circa horse taped mightly',
    href: '#',
    image: 'images/blog-1.png',
  },
  {
    id: 2,
    date: '21 August, 2020',
    name: 'SaberAli',
    title: 'Top esssential Trends in 2021',
    description: 'More off this less hello samlande lied much over tightly circa horse taped mightly',
    href: '#',
    image: 'images/blog-2.png',
  },
  {
    id: 3,
    date: '21 August, 2020',
    name: 'SaberAli',
    title: 'Top esssential Trends in 2021',
    description: 'More off this less hello samlande lied much over tightly circa horse taped mightly',
    href: '#',
    image: 'images/blog-3.png',
  },
]

export const DataFooter = [
  {
    title: 'Categories',
    items: [
      {
        title: 'Laptop & Computers',
        href: '#',
      },
      {
        title: 'Cameras & Photography',
        href: '#',
      },
      {
        title: 'Smart Phones & Tablets',
        href: '#',
      },
      {
        title: 'Video Games & Consoles',
        href: '#',
      },
      {
        title: 'Waterproof Headphones',
        href: '#',
      },
    ],
  },
  {
    title: 'Customer Care',
    items: [
      {
        title: 'My Account',
        href: '#',
      },
      {
        title: 'Discount',
        href: '#',
      },
      {
        title: 'Returns',
        href: '#',
      },
      {
        title: 'Orders History',
        href: '#',
      },
      {
        title: 'Order Tracking',
        href: '#',
      },
    ],
  },
  {
    title: 'Pages',
    items: [
      {
        title: 'Blog',
        href: '#',
      },
      {
        title: 'Browse the Shop',
        href: '#',
      },
      {
        title: 'Category',
        href: '#',
      },
      {
        title: 'Pre-Built Pages',
        href: '#',
      },
      {
        title: 'Visual Composer Elements',
        href: '#',
      },
      {
        title: 'WooCommerce Pages',
        href: '#',
      },
    ],
  },
]
export const DataShopDefault = [
  {
    id: 1,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Deserunt elit labore tempor duis esse consequat.',
    image: 'images/shop1.png',
  },
  {
    id: 2,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Mollit amet anim cillum ea eiusmod culpa.',
    image: 'images/shop2.png',
  },
  {
    id: 3,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Laboris ad nostrud laborum duis minim aliquip.',
    image: 'images/shop3.png',
  },
  {
    id: 4,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Incididunt sunt nulla pariatur ipsum amet sint.',
    image: 'images/shop4.png',
  },
  {
    id: 5,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Quis deserunt cupidatat enim non ex in.',
    image: 'images/shop1.png',
  },
  {
    id: 6,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Aliqua voluptate commodo quis ipsum duis do.',
    image: 'images/shop2.png',
  },
  {
    id: 7,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Reprehenderit commodo ex fugiat ullamco minim et.',
    image: 'images/shop3.png',
  },
  {
    id: 8,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Est veniam incididunt consequat incididunt ut eu.',
    image: 'images/shop4.png',
  },
  {
    id: 9,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Irure minim minim nostrud ad cillum labore.',
    image: 'images/shop1.png',
  },
  {
    id: 10,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Cillum ipsum sunt qui aute quis deserunt.',
    image: 'images/shop2.png',
  },
  {
    id: 11,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Incididunt labore nisi nostrud in duis voluptate.',
    image: 'images/shop3.png',
  },
  {
    id: 12,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Pariatur laborum dolor consequat adipisicing dolore.',
    image: 'images/shop4.png',
  },
  {
    id: 13,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'In enim Lorem ea in reprehenderit id.',
    image: 'images/shop1.png',
  },
  {
    id: 14,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Non nulla minim fugiat cupidatat quis culpa.',
    image: 'images/shop2.png',
  },
  {
    id: 15,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Aute eiusmod nostrud nisi et occaecat.',
    image: 'images/shop3.png',
  },
  {
    id: 16,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Commodo ut duis excepteur adipisicing. incididunt.',
    image: 'images/shop4.png',
  },
  {
    id: 17,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Nisi sunt labore voluptate laborum fugiat nisi.',
    image: 'images/shop1.png',
  },
  {
    id: 18,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Et nostrud sunt reprehenderit quis aliqua.',
    image: 'images/shop2.png',
  },
  {
    id: 19,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Eiusmod exercitation ex cillum eiusmod. consequat.',
    image: 'images/shop3.png',
  },
  {
    id: 20,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    description: 'Tempor consectetur nisi ex pariatur reprehenderit consectetur.',
    image: 'images/shop4.png',
  },
]
export const DataSidebar = [
  {
    title: 'Product Brand',
    type: 'checkbox',
    listItem: [
      {
        item: 'Coaster Futniture',
        tags: 'coaster-futniture',
      },
      {
        item: 'Fusion Dot Hight Fashion',
        tags: 'fusion-dot-hight-fashion',
      },
      {
        item: 'Unique Furniture Restor',
        tags: 'unique-furniture-restor',
      },
      {
        item: 'Dream Furniture Flipping',
        tags: 'dream-furniture-flipping',
      },
      {
        item: 'Young Repurposed',
        tags: 'young-repurposed',
      },
      {
        item: 'Greem DIY furniture',
        tags: 'greem-diy-furniture',
      },
    ],
  },
  {
    title: 'Discount Offer',
    type: 'checkbox',
    listItem: [
      {
        item: '20% Cashback',
        tags: '20%-cashback',
      },
      {
        item: '5% Cashback Offer',
        tags: '5%-cashback-offer',
      },
      {
        item: '25% discount Offer',
        tags: '25%-discount-offer',
      },
    ],
  },
  {
    title: 'Rating Item',
    type: 'rating',
    listItem: [
      {
        item: 5,
        numberProduct: 2341,
      },
      {
        item: 4,
        numberProduct: 1726,
      },
      {
        item: 3,
        numberProduct: 258,
      },
      {
        item: 2,
        numberProduct: 25,
      },
    ],
  },
  {
    title: 'Categories',
    type: 'checkbox',
    listItem: [
      {
        item: 'Prestashop',
        tags: 'prestashop',
      },
      {
        item: 'Magento',
        tags: 'magento',
      },
      {
        item: 'Bigcommerce',
        tags: 'bigcommerce',
      },
      {
        item: 'osCommerce',
        tags: 'oscommerce',
      },
      {
        item: '3dcart',
        tags: '3dcart',
      },
      {
        item: 'Bags',
        tags: 'bags',
      },
      {
        item: 'Accessories',
        tags: 'accessories',
      },
      {
        item: 'Jewellery',
        tags: 'jewellery',
      },
      {
        item: 'Watches',
        tags: 'watches',
      },
    ],
  },
  {
    title: 'Price Filter',
    type: 'price',
    listItem: null,
  },
]
export const DataDetailProduct = [
  {
    title: 'Playwood arm chair',
    rating: 5,
    price: 32,
    old_price: 32,
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    description:
      'Commodo do esse elit sit nulla labore irure deserunt fugiat sunt proident excepteur ad. Aliquip sint veniam adipisicing fugiat ad aliqua quis laboris. Culpa in ipsum ipsum non pariatur nulla. Sunt proident sint incididunt exercitation adipisicing ea. Exercitation et occaecat voluptate elit.',
    categories: 'Commodo do esse elit sit nulla labore irure deserunt fugiat sunt proident excepteur ad. ',
    tags: [
      {
        title: 'Tag 1',
        key: 'tag-1',
      },
      {
        title: 'Tag 2',
        key: 'tag-2',
      },
      {
        title: 'Tag 3',
        key: 'tag-3',
      },
      {
        title: 'Tag 4',
        key: 'tag-4',
      },
    ],
    images: ['/images/detailProduct1.png', '/images/detailProduct2.png', '/images/detailProduct3.png', '/images/detailProduct4.png'],
  },
]

export const DataRelatedProduct = [
  {
    id: 1,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    image: '/images/featuredProducts-1.png',
  },
  {
    id: 2,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    image: '/images/featuredProducts-2.png',
  },
  {
    id: 3,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    image: '/images/featuredProducts-3.png',
  },
  {
    id: 4,
    title: 'Cantilever chair',
    slug: 'camtilever-chair',
    colors: ['#05E6B7', '#F701A8', '#00009D'],
    code: 'Y523201',
    price: 42,
    old_price: null,
    href: '#',
    image: '/images/featuredProducts-4.png',
  },
]
export const DataCart = [
  {
    id: 1,
    image: '/images/featuredProducts-4.png',
    name: 'Cantilever chair',
    slug: 'camtilever-chair',
    color: '#05E6B7',
    price: 32,
    quantity: 1,
    time: '10/05/2022',
  },
  {
    id: 2,
    image: '/images/featuredProducts-4.png',
    name: 'Cantilever chair',
    slug: 'camtilever-chair',
    color: '#05E6B7',
    price: 32,
    quantity: 1,
    time: '10/05/2022',
  },
  {
    id: 3,
    image: '/images/featuredProducts-4.png',
    name: 'Cantilever chair',
    slug: 'camtilever-chair',
    color: '#05E6B7',
    price: 32,
    quantity: 1,
    time: '10/05/2022',
  },
  {
    id: 4,
    image: '/images/featuredProducts-4.png',
    name: 'Cantilever chair',
    slug: 'camtilever-chair',
    color: '#05E6B7',
    price: 32,
    quantity: 1,
    time: '10/05/2022',
  },
]
