export const ADMIN_QUERY_USER = 'ADMIN_QUERY_USER'
export const ADMIN_QUERY_PRODUCT_BY_USER_ID = 'ADMIN_QUERY_PRODUCT_BY_USER_ID'
export const ADMIN_QUERY_ALL_PRODUCT = 'ADMIN_QUERY_ALL_PRODUCT'
export const ADMIN_QUERY_ALL_PRODUCT_PORTFOLIO = 'ADMIN_QUERY_ALL_PRODUCT_PORTFOLIO'
